[package]
name = "rlox"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
once_cell = "1.20.2"
thiserror = "2.0.11"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
